.TH "NOC" "1" "Jun 23, 2013" "noc user manual" ""
.SH NAME
.PP
noc \- Count number of commands a day
.SH SYNOPSIS
.PP
noc [OPTIONS] \f[I]num\f[]
.SH DESCRIPTION
.PP
This command computes the number of commands you type in 24 hours.
Without any argument, show the number of commands of today.
Otherwise, view retroactively numbers shown in the first argument.
.PP
On GitHub: <http://github.com/b4b4r07/noc>
.PP
.SH OPTIONS
Here is a summary of all the options. The following options are available:
.TP 12
.BI -h
Display help and exit.
.TP
.BI -l\ num
View the history of a number of arguments. Running the -l option without parameters displays 10 history.
.SH SEE ALSO
.PP
https://github.com/b4b4r07/noc/blob/master/README.md
.SH LICENSE AND COPYRIGHT
.PP
Copyright (c) 2013, b4b4r07 <b4b4r07@gmail.com>
.PP
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:
.PP
Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.
.PP
Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.
.PP
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER ``AS IS\[aq]\[aq] AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
.SH AUTHORS
B4B4R07 <b4b4r07@gmail.com>.
